lmmentel/mendeleev

- mendeleev/ion.py
> Fixed a typo in Ion exception

- mendeleev/models.py
> Fix import warning for declarative_base

- .github/workflows/main.yml
- poetry.lock
- pyproject.toml
> Add vis extra

- mendeleev/electronegativity.py
- mendeleev/models.py
- tests/test_electronegativity.py
> Fix Mulliken electronegativity

- README.md
@Eben60 anything you would like to add?
> Add Mendeleev.jl to README

- docs/source/api/models.rst
- docs/source/data_access.rst
Fixes #178
- add `phasetransitions` table to data access docs 
- add `IsotopeDecayMode` to model docs
> [DOC] Add `phasetransitions` table to data access docs

- docs/source/data_access.rst
> [DOC] Correct the data export instructions

- CHANGES.rst
> [FIX] Typo in changelog

- poetry.lock
- pyproject.toml
Fixes #195
- **Add pytest-xdist and configure to use all cores**
> [MNT] Add pytest-xdist to dev deps and configure to use all cores

- docs/source/api/mendeleev.cli.rst
- docs/source/api/mendeleev.db.rst
- docs/source/api/mendeleev.econf.rst
- docs/source/api/mendeleev.electronegativity.rst
- docs/source/api/mendeleev.fetch.rst
- docs/source/api/mendeleev.mendeleev.rst
- docs/source/api/mendeleev.utils.rst
- mendeleev/models.py
> [DOC] Update docs for atomic scattering factor

- docs/source/data.rst
> [FIX] Fix footnotes on data doc page

- mendeleev/models.py
- poetry.lock
- pyproject.toml
- tests/test_electronegativity.py
- tests/test_element.py
- **refactor fixtures**
- **update tests**
- **add test for electronegativity functions**
- **:lipstick:**
- **add pytest-cov**
Fixes #
-
-
-
> [MNT] Increase test coverage

- README.md
- docs/source/data_access.rst
> [DOC] Add a reference to `mendeleev-data` repo

- docs/source/conf.py
- docs/source/index.rst
> [DOC] Clean-up tutorial docs

- tasks.py
> [FIX] Correct path for sqldiff

- .github/workflows/main.yml
context: https://docs.pypi.org/trusted-publishers/using-a-publisher/
> [MNT] Switch to PyPI Trusted Publishing

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> [DOC] Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

- mendeleev/models.py
- poetry.lock
Fixes #81 
- add `isotope` hybrid method to Element
> [ENH] Add isotope method to access a single isotope from Element

- mendeleev/electronegativity.py
- mendeleev/models.py
- tests/test_electronegativity.py
> [MNT] Refactor and speed up Sanderson's electronegativity calculation

- CONTRIBUTING.md
- docs/requirements.txt
- docs/source/CONTRIBUTING.md
- docs/source/conf.py
- docs/source/index.rst
> [DOC] Add contributor's guide to the docs

- mendeleev/models.py
- introduce `ReprMixin` class implementing `__repr__` for all sqlalchemy models
> [ENH] Refactor __repr__ to ReprMixin for all models
